// <auto-generated />
namespace BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seeddefaultdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeddefaultdata));
        
        string IMigrationMetadata.Id
        {
            get { return "202007151119424_seed-default-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
