// <auto-generated />
namespace BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202007110239285_init-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
